// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/20       [336404]
Creator        : admorris
Date           : Thu Sep 25 18:20:39 2014
Host           : Linux lxbuild101.cern.ch 2.6.32-358.2.1.el6.x86_64 #1 SMP Wed Mar 13 08:24:06 CET 2013 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/admorris/pkphi/BDT
Training events: 81321
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
Lb_ln_FDCHI2                  Lb_ln_FDCHI2                  Lb_ln_FDCHI2                  Lb_ln_FDCHI2                                                    'F'    [6.21461105347,16.1434707642]
Lb_ln_IPCHI2                  Lb_ln_IPCHI2                  Lb_ln_IPCHI2                  Lb_ln_IPCHI2                                                    'F'    [-25,2.70803785324]
Lb_ln_VCHI2                   Lb_ln_VCHI2                   Lb_ln_VCHI2                   Lb_ln_VCHI2                                                     'F'    [-2.15230298042,4.84921884537]
Lb_PT                         Lb_PT                         Lb_PT                         Lb_PT                                                           'F'    [0.00230835448019,526.518066406]
h_min_PT                      h_min_PT                      h_min_PT                      h_min_PT                                                        'F'    [0.400004982948,25.5063648224]
h_min_ln_IP                   h_min_ln_IP                   h_min_ln_IP                   h_min_ln_IP                                                     'F'    [-3.92155647278,2.56720423698]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 6 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Lb_ln_FDCHI2", "Lb_ln_IPCHI2", "Lb_ln_VCHI2", "Lb_PT", "h_min_PT", "h_min_ln_IP" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][6];
   double fMax_1[3][6];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[12][7];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][12];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 7; fWeights[0] = new double[7]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.205390583736611;
   fWeightMatrix0to1[1][0] = 0.622311381114038;
   fWeightMatrix0to1[2][0] = 1.95768981836336;
   fWeightMatrix0to1[3][0] = -0.0112381807486564;
   fWeightMatrix0to1[4][0] = -0.923029216483184;
   fWeightMatrix0to1[5][0] = 0.202685582796289;
   fWeightMatrix0to1[6][0] = -0.1671815571155;
   fWeightMatrix0to1[7][0] = 0.333045784452323;
   fWeightMatrix0to1[8][0] = 0.336136844169008;
   fWeightMatrix0to1[9][0] = -0.43828366750033;
   fWeightMatrix0to1[10][0] = -1.01276935771108;
   fWeightMatrix0to1[0][1] = -2.10262906590857;
   fWeightMatrix0to1[1][1] = -0.41503783326719;
   fWeightMatrix0to1[2][1] = -3.77632158350474;
   fWeightMatrix0to1[3][1] = -3.23185862889847;
   fWeightMatrix0to1[4][1] = -1.04585497614551;
   fWeightMatrix0to1[5][1] = -0.351352065094215;
   fWeightMatrix0to1[6][1] = 5.05173678221838;
   fWeightMatrix0to1[7][1] = -0.566841467992236;
   fWeightMatrix0to1[8][1] = 1.70292852076531;
   fWeightMatrix0to1[9][1] = 0.345995182593144;
   fWeightMatrix0to1[10][1] = -3.71506485205993;
   fWeightMatrix0to1[0][2] = 0.272718739157975;
   fWeightMatrix0to1[1][2] = -0.0067603021371027;
   fWeightMatrix0to1[2][2] = -3.02610658425899;
   fWeightMatrix0to1[3][2] = 0.0244818929502363;
   fWeightMatrix0to1[4][2] = 1.70758490300299;
   fWeightMatrix0to1[5][2] = -0.0522249899087154;
   fWeightMatrix0to1[6][2] = 0.458270838887746;
   fWeightMatrix0to1[7][2] = 0.395112089704764;
   fWeightMatrix0to1[8][2] = -0.302315688701635;
   fWeightMatrix0to1[9][2] = 3.43205063513787;
   fWeightMatrix0to1[10][2] = 1.00585165383202;
   fWeightMatrix0to1[0][3] = -4.19538431772559;
   fWeightMatrix0to1[1][3] = -0.796054659849692;
   fWeightMatrix0to1[2][3] = -2.29272599861072;
   fWeightMatrix0to1[3][3] = -2.43633497824995;
   fWeightMatrix0to1[4][3] = 3.1932309219302;
   fWeightMatrix0to1[5][3] = -1.9397953432386;
   fWeightMatrix0to1[6][3] = 5.60351001247051;
   fWeightMatrix0to1[7][3] = 2.58798025868986;
   fWeightMatrix0to1[8][3] = 2.71008888721266;
   fWeightMatrix0to1[9][3] = 1.41542189700906;
   fWeightMatrix0to1[10][3] = -2.11025543587014;
   fWeightMatrix0to1[0][4] = -2.29850878029764;
   fWeightMatrix0to1[1][4] = -2.97371124785194;
   fWeightMatrix0to1[2][4] = 0.938497091574379;
   fWeightMatrix0to1[3][4] = 8.29759908024512;
   fWeightMatrix0to1[4][4] = 4.31330272586375;
   fWeightMatrix0to1[5][4] = 1.09620424802631;
   fWeightMatrix0to1[6][4] = 4.43294070195095;
   fWeightMatrix0to1[7][4] = 2.74477881628238;
   fWeightMatrix0to1[8][4] = -2.53143166721086;
   fWeightMatrix0to1[9][4] = 1.25165768516493;
   fWeightMatrix0to1[10][4] = -4.15729460622418;
   fWeightMatrix0to1[0][5] = 2.816196152993;
   fWeightMatrix0to1[1][5] = 0.109984801253541;
   fWeightMatrix0to1[2][5] = -0.328849324007583;
   fWeightMatrix0to1[3][5] = 3.05248382660966;
   fWeightMatrix0to1[4][5] = 1.65159008029167;
   fWeightMatrix0to1[5][5] = -0.456525646129979;
   fWeightMatrix0to1[6][5] = 1.45898897561024;
   fWeightMatrix0to1[7][5] = 0.697826626325423;
   fWeightMatrix0to1[8][5] = 0.704100836406211;
   fWeightMatrix0to1[9][5] = 1.87708467585588;
   fWeightMatrix0to1[10][5] = 0.994385841155075;
   fWeightMatrix0to1[0][6] = -3.30757251536291;
   fWeightMatrix0to1[1][6] = -2.18431682092309;
   fWeightMatrix0to1[2][6] = 5.16326381066313;
   fWeightMatrix0to1[3][6] = 9.42710791619383;
   fWeightMatrix0to1[4][6] = 7.6874558996433;
   fWeightMatrix0to1[5][6] = -0.768008328733145;
   fWeightMatrix0to1[6][6] = 4.39037950454205;
   fWeightMatrix0to1[7][6] = 5.52775188091115;
   fWeightMatrix0to1[8][6] = -0.208004310235368;
   fWeightMatrix0to1[9][6] = 1.00624165912619;
   fWeightMatrix0to1[10][6] = -4.71326041413734;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.4618942776873;
   fWeightMatrix1to2[0][1] = 0.315957500651165;
   fWeightMatrix1to2[0][2] = 0.196491907650479;
   fWeightMatrix1to2[0][3] = 0.675963042314314;
   fWeightMatrix1to2[0][4] = 0.710866815957516;
   fWeightMatrix1to2[0][5] = -0.192343035707991;
   fWeightMatrix1to2[0][6] = -0.586575007748641;
   fWeightMatrix1to2[0][7] = -0.420712649232734;
   fWeightMatrix1to2[0][8] = 0.343124815172264;
   fWeightMatrix1to2[0][9] = -0.0761941520280176;
   fWeightMatrix1to2[0][10] = -0.378865477778763;
   fWeightMatrix1to2[0][11] = -0.894152873817972;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 6.21510219574;
   fMax_1[0][0] = 13.4388933182;
   fMin_1[1][0] = 6.21461105347;
   fMax_1[1][0] = 16.1434707642;
   fMin_1[2][0] = 6.21461105347;
   fMax_1[2][0] = 16.1434707642;
   fMin_1[0][1] = -8.28906822205;
   fMax_1[0][1] = 2.70671439171;
   fMin_1[1][1] = -25;
   fMax_1[1][1] = 2.70803785324;
   fMin_1[2][1] = -25;
   fMax_1[2][1] = 2.70803785324;
   fMin_1[0][2] = 0.0443349517882;
   fMax_1[0][2] = 4.57816457748;
   fMin_1[1][2] = -2.15230298042;
   fMax_1[1][2] = 4.84921884537;
   fMin_1[2][2] = -2.15230298042;
   fMax_1[2][2] = 4.84921884537;
   fMin_1[0][3] = 0.0612068846822;
   fMax_1[0][3] = 53.1874465942;
   fMin_1[1][3] = 0.00230835448019;
   fMax_1[1][3] = 526.518066406;
   fMin_1[2][3] = 0.00230835448019;
   fMax_1[2][3] = 526.518066406;
   fMin_1[0][4] = 0.400072216988;
   fMax_1[0][4] = 8.22924232483;
   fMin_1[1][4] = 0.400004982948;
   fMax_1[1][4] = 25.5063648224;
   fMin_1[2][4] = 0.400004982948;
   fMax_1[2][4] = 25.5063648224;
   fMin_1[0][5] = -3.8420445919;
   fMax_1[0][5] = 1.09952735901;
   fMin_1[1][5] = -3.92155647278;
   fMax_1[1][5] = 2.56720423698;
   fMin_1[2][5] = -3.92155647278;
   fMax_1[2][5] = 2.56720423698;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 6;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<6;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
