// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/20       [336404]
Creator        : admorris
Date           : Mon May 18 22:03:46 2015
Host           : Linux lxbuild101.cern.ch 2.6.32-358.2.1.el6.x86_64 #1 SMP Wed Mar 13 08:24:06 CET 2013 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/admorris/BsphiKK/mva
Training events: 22661
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
B_s0_ln_FDCHI2                B_s0_ln_FDCHI2                B_s0_ln_FDCHI2                B_s0_ln_FDCHI2                                                  'F'    [5.52172231674,14.3609724045]
B_s0_ln_IPCHI2                B_s0_ln_IPCHI2                B_s0_ln_IPCHI2                B_s0_ln_IPCHI2                                                  'F'    [-8.89601802826,2.99566316605]
B_s0_ln_EVCHI2                B_s0_ln_EVCHI2                B_s0_ln_EVCHI2                B_s0_ln_EVCHI2                                                  'F'    [-4.45417881012,2.30202627182]
B_s0_PT_fiveGeV               B_s0_PT_fiveGeV               B_s0_PT_fiveGeV               B_s0_PT_fiveGeV                                                 'F'    [0.00495414808393,14.9297647476]
B_s0_Eta                      B_s0_Eta                      B_s0_Eta                      B_s0_Eta                                                        'F'    [1.91479802132,8.57907009125]
minK_PT_GeV                   minK_PT_GeV                   minK_PT_GeV                   minK_PT_GeV                                                     'F'    [0.497218757868,10.7027111053]
minK_ln_IPCHI2                minK_ln_IPCHI2                minK_ln_IPCHI2                minK_ln_IPCHI2                                                  'F'    [-8.81861114502,10.0275764465]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "B_s0_ln_FDCHI2", "B_s0_ln_IPCHI2", "B_s0_ln_EVCHI2", "B_s0_PT_fiveGeV", "B_s0_Eta", "minK_PT_GeV", "minK_ln_IPCHI2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][7];
   double fMax_1[3][7];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[13][8];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][13];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 8; fWeights[0] = new double[8]; 
   fLayerSize[1] = 13; fWeights[1] = new double[13]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.100951389540295;
   fWeightMatrix0to1[1][0] = 1.70264027053471;
   fWeightMatrix0to1[2][0] = 0.926242544961148;
   fWeightMatrix0to1[3][0] = 1.76193859254685;
   fWeightMatrix0to1[4][0] = -1.44968358720229;
   fWeightMatrix0to1[5][0] = -1.84548808153012;
   fWeightMatrix0to1[6][0] = 0.208860066868436;
   fWeightMatrix0to1[7][0] = 1.19889803304937;
   fWeightMatrix0to1[8][0] = -0.576396892302165;
   fWeightMatrix0to1[9][0] = -1.02060967330516;
   fWeightMatrix0to1[10][0] = -1.27625247971385;
   fWeightMatrix0to1[11][0] = -0.375070346836963;
   fWeightMatrix0to1[0][1] = 0.283390959660369;
   fWeightMatrix0to1[1][1] = -0.882496278087472;
   fWeightMatrix0to1[2][1] = 0.125270772899147;
   fWeightMatrix0to1[3][1] = 0.720962480329355;
   fWeightMatrix0to1[4][1] = -0.178546765979873;
   fWeightMatrix0to1[5][1] = 2.59472252500737;
   fWeightMatrix0to1[6][1] = -0.637606497988725;
   fWeightMatrix0to1[7][1] = 1.07573317994584;
   fWeightMatrix0to1[8][1] = -0.383527315501788;
   fWeightMatrix0to1[9][1] = -0.830322215136689;
   fWeightMatrix0to1[10][1] = 0.539191417614165;
   fWeightMatrix0to1[11][1] = 0.727669785341873;
   fWeightMatrix0to1[0][2] = -2.05778064131879;
   fWeightMatrix0to1[1][2] = -0.577207537704353;
   fWeightMatrix0to1[2][2] = 0.97851073658171;
   fWeightMatrix0to1[3][2] = -1.11097302622732;
   fWeightMatrix0to1[4][2] = -1.70610642266351;
   fWeightMatrix0to1[5][2] = 1.89267029056608;
   fWeightMatrix0to1[6][2] = 1.21841318783931;
   fWeightMatrix0to1[7][2] = 1.40609862670103;
   fWeightMatrix0to1[8][2] = -0.0374063462179868;
   fWeightMatrix0to1[9][2] = 0.119370929585622;
   fWeightMatrix0to1[10][2] = 0.500128540437436;
   fWeightMatrix0to1[11][2] = 0.0112565347367355;
   fWeightMatrix0to1[0][3] = -1.72659490796183;
   fWeightMatrix0to1[1][3] = 1.45917319486215;
   fWeightMatrix0to1[2][3] = -1.35686994070733;
   fWeightMatrix0to1[3][3] = 1.05829309282636;
   fWeightMatrix0to1[4][3] = 1.32375993953618;
   fWeightMatrix0to1[5][3] = -3.96287401233541;
   fWeightMatrix0to1[6][3] = 1.30063911386151;
   fWeightMatrix0to1[7][3] = 0.539494158131714;
   fWeightMatrix0to1[8][3] = -0.946531856565593;
   fWeightMatrix0to1[9][3] = -0.932058338261518;
   fWeightMatrix0to1[10][3] = 0.933566385397365;
   fWeightMatrix0to1[11][3] = -0.177929427834888;
   fWeightMatrix0to1[0][4] = -0.196495285647295;
   fWeightMatrix0to1[1][4] = 2.36788308978328;
   fWeightMatrix0to1[2][4] = 0.652763703139054;
   fWeightMatrix0to1[3][4] = 1.34893773153463;
   fWeightMatrix0to1[4][4] = -1.27228829129809;
   fWeightMatrix0to1[5][4] = 1.7478303682724;
   fWeightMatrix0to1[6][4] = -0.728349338856911;
   fWeightMatrix0to1[7][4] = -1.44155866654043;
   fWeightMatrix0to1[8][4] = -1.65752404691025;
   fWeightMatrix0to1[9][4] = -2.16549767378436;
   fWeightMatrix0to1[10][4] = 1.38538897278627;
   fWeightMatrix0to1[11][4] = 1.33513246397722;
   fWeightMatrix0to1[0][5] = 0.524664839921569;
   fWeightMatrix0to1[1][5] = 0.416490571425311;
   fWeightMatrix0to1[2][5] = -1.13471745563875;
   fWeightMatrix0to1[3][5] = 0.62888256465333;
   fWeightMatrix0to1[4][5] = 1.54970287364427;
   fWeightMatrix0to1[5][5] = -1.75077532922076;
   fWeightMatrix0to1[6][5] = -0.128913677274143;
   fWeightMatrix0to1[7][5] = -1.97657727658712;
   fWeightMatrix0to1[8][5] = 0.401303977729487;
   fWeightMatrix0to1[9][5] = -0.255733481996708;
   fWeightMatrix0to1[10][5] = -0.213273582075942;
   fWeightMatrix0to1[11][5] = -0.640333290750459;
   fWeightMatrix0to1[0][6] = 0.512097700379259;
   fWeightMatrix0to1[1][6] = 0.549877077928361;
   fWeightMatrix0to1[2][6] = 1.83767848230926;
   fWeightMatrix0to1[3][6] = -0.348223861109981;
   fWeightMatrix0to1[4][6] = -1.95036421212336;
   fWeightMatrix0to1[5][6] = -2.76258787063059;
   fWeightMatrix0to1[6][6] = 0.599080428643021;
   fWeightMatrix0to1[7][6] = 0.744745216399451;
   fWeightMatrix0to1[8][6] = 1.82263569583014;
   fWeightMatrix0to1[9][6] = 0.869884544791634;
   fWeightMatrix0to1[10][6] = 0.626019131208681;
   fWeightMatrix0to1[11][6] = -1.30486667260288;
   fWeightMatrix0to1[0][7] = -0.856051160202021;
   fWeightMatrix0to1[1][7] = -0.8479247559606;
   fWeightMatrix0to1[2][7] = 1.74294300914012;
   fWeightMatrix0to1[3][7] = -1.09202684700992;
   fWeightMatrix0to1[4][7] = -2.09183768862103;
   fWeightMatrix0to1[5][7] = -8.24955825419389;
   fWeightMatrix0to1[6][7] = 0.107450940224411;
   fWeightMatrix0to1[7][7] = 0.87026878464136;
   fWeightMatrix0to1[8][7] = 1.88462082531681;
   fWeightMatrix0to1[9][7] = -0.682540591246204;
   fWeightMatrix0to1[10][7] = -0.966834546721325;
   fWeightMatrix0to1[11][7] = 0.371123925172491;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.43121721514627;
   fWeightMatrix1to2[0][1] = -1.05553782805336;
   fWeightMatrix1to2[0][2] = -1.52953538819798;
   fWeightMatrix1to2[0][3] = -0.0931586917057596;
   fWeightMatrix1to2[0][4] = -1.14266897725092;
   fWeightMatrix1to2[0][5] = -0.637129975409557;
   fWeightMatrix1to2[0][6] = -0.702495481833354;
   fWeightMatrix1to2[0][7] = 0.551949078479042;
   fWeightMatrix1to2[0][8] = -1.01847345617766;
   fWeightMatrix1to2[0][9] = 0.245884023742345;
   fWeightMatrix1to2[0][10] = 0.0611587525291158;
   fWeightMatrix1to2[0][11] = -0.421532448304026;
   fWeightMatrix1to2[0][12] = -0.139408425147165;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5.52172231674;
   fMax_1[0][0] = 14.1277580261;
   fMin_1[1][0] = 5.52216863632;
   fMax_1[1][0] = 14.3609724045;
   fMin_1[2][0] = 5.52172231674;
   fMax_1[2][0] = 14.3609724045;
   fMin_1[0][1] = -8.89601802826;
   fMax_1[0][1] = 2.99134349823;
   fMin_1[1][1] = -4.52225160599;
   fMax_1[1][1] = 2.99566316605;
   fMin_1[2][1] = -8.89601802826;
   fMax_1[2][1] = 2.99566316605;
   fMin_1[0][2] = -4.45417881012;
   fMax_1[0][2] = 2.30202627182;
   fMin_1[1][2] = -2.44079780579;
   fMax_1[1][2] = 2.29882144928;
   fMin_1[2][2] = -4.45417881012;
   fMax_1[2][2] = 2.30202627182;
   fMin_1[0][3] = 0.0238515790552;
   fMax_1[0][3] = 14.9297647476;
   fMin_1[1][3] = 0.00495414808393;
   fMax_1[1][3] = 8.31843662262;
   fMin_1[2][3] = 0.00495414808393;
   fMax_1[2][3] = 14.9297647476;
   fMin_1[0][4] = 1.91479802132;
   fMax_1[0][4] = 6.49894762039;
   fMin_1[1][4] = 2.06325936317;
   fMax_1[1][4] = 8.57907009125;
   fMin_1[2][4] = 1.91479802132;
   fMax_1[2][4] = 8.57907009125;
   fMin_1[0][5] = 0.498860865831;
   fMax_1[0][5] = 10.7027111053;
   fMin_1[1][5] = 0.497218757868;
   fMax_1[1][5] = 4.52298927307;
   fMin_1[2][5] = 0.497218757868;
   fMax_1[2][5] = 10.7027111053;
   fMin_1[0][6] = -5.64627838135;
   fMax_1[0][6] = 10.0275764465;
   fMin_1[1][6] = -8.81861114502;
   fMax_1[1][6] = 8.83983802795;
   fMin_1[2][6] = -8.81861114502;
   fMax_1[2][6] = 10.0275764465;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 7;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<7;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
