// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/20       [336404]
Creator        : admorris
Date           : Mon May 18 12:41:22 2015
Host           : Linux lxbuild101.cern.ch 2.6.32-358.2.1.el6.x86_64 #1 SMP Wed Mar 13 08:24:06 CET 2013 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/admorris/BsphiKK/mva
Training events: 22661
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
B_s0_ln_FDCHI2                B_s0_ln_FDCHI2                B_s0_ln_FDCHI2                B_s0_ln_FDCHI2                                                  'F'    [5.52172231674,14.3609724045]
B_s0_ln_IPCHI2                B_s0_ln_IPCHI2                B_s0_ln_IPCHI2                B_s0_ln_IPCHI2                                                  'F'    [-8.89601802826,2.99566316605]
B_s0_ln_EVCHI2                B_s0_ln_EVCHI2                B_s0_ln_EVCHI2                B_s0_ln_EVCHI2                                                  'F'    [-4.45417881012,2.30202627182]
B_s0_PT_GeV                   B_s0_PT_GeV                   B_s0_PT_GeV                   B_s0_PT_GeV                                                     'F'    [0.0247707404196,74.6488189697]
B_s0_Eta                      B_s0_Eta                      B_s0_Eta                      B_s0_Eta                                                        'F'    [1.91479802132,8.57907009125]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "B_s0_ln_FDCHI2", "B_s0_ln_IPCHI2", "B_s0_ln_EVCHI2", "B_s0_PT_GeV", "B_s0_Eta" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[11][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.433976639589205;
   fWeightMatrix0to1[1][0] = 1.08899933926026;
   fWeightMatrix0to1[2][0] = 0.742660378056894;
   fWeightMatrix0to1[3][0] = 1.38211932501614;
   fWeightMatrix0to1[4][0] = -1.07325497918124;
   fWeightMatrix0to1[5][0] = -1.21664813501533;
   fWeightMatrix0to1[6][0] = -2.23499267065949;
   fWeightMatrix0to1[7][0] = 1.03571536910427;
   fWeightMatrix0to1[8][0] = -0.0336983614183865;
   fWeightMatrix0to1[9][0] = -0.709728053423484;
   fWeightMatrix0to1[0][1] = 0.500180099004932;
   fWeightMatrix0to1[1][1] = -1.03472349262433;
   fWeightMatrix0to1[2][1] = -0.867648037445148;
   fWeightMatrix0to1[3][1] = 0.347355727992853;
   fWeightMatrix0to1[4][1] = -0.136265044880266;
   fWeightMatrix0to1[5][1] = 0.67749917688166;
   fWeightMatrix0to1[6][1] = 2.57592541132102;
   fWeightMatrix0to1[7][1] = 1.7706272896756;
   fWeightMatrix0to1[8][1] = 0.913612210573737;
   fWeightMatrix0to1[9][1] = 0.692107451040412;
   fWeightMatrix0to1[0][2] = -2.18743314974849;
   fWeightMatrix0to1[1][2] = -0.47764824895101;
   fWeightMatrix0to1[2][2] = 1.39943991783246;
   fWeightMatrix0to1[3][2] = 0.823009721060033;
   fWeightMatrix0to1[4][2] = -0.798180603430143;
   fWeightMatrix0to1[5][2] = -0.199879419376529;
   fWeightMatrix0to1[6][2] = 1.72049324692389;
   fWeightMatrix0to1[7][2] = -1.60503879336177;
   fWeightMatrix0to1[8][2] = -1.62408029389012;
   fWeightMatrix0to1[9][2] = 0.441433067420632;
   fWeightMatrix0to1[0][3] = 0.0349112933966093;
   fWeightMatrix0to1[1][3] = 1.07675650463567;
   fWeightMatrix0to1[2][3] = -0.409889618677415;
   fWeightMatrix0to1[3][3] = 0.937517775993185;
   fWeightMatrix0to1[4][3] = 0.768151377277975;
   fWeightMatrix0to1[5][3] = -1.19134622270345;
   fWeightMatrix0to1[6][3] = -3.4967509418582;
   fWeightMatrix0to1[7][3] = 0.730299337538023;
   fWeightMatrix0to1[8][3] = -0.733281095753603;
   fWeightMatrix0to1[9][3] = 1.01697833689436;
   fWeightMatrix0to1[0][4] = 0.3604730028272;
   fWeightMatrix0to1[1][4] = -0.484388845281526;
   fWeightMatrix0to1[2][4] = 1.46082516871369;
   fWeightMatrix0to1[3][4] = 0.634099006853054;
   fWeightMatrix0to1[4][4] = -0.00965952058088996;
   fWeightMatrix0to1[5][4] = -0.263063547448781;
   fWeightMatrix0to1[6][4] = 1.26019460028386;
   fWeightMatrix0to1[7][4] = 1.14405242749115;
   fWeightMatrix0to1[8][4] = 1.04902194432008;
   fWeightMatrix0to1[9][4] = 2.3398389394548;
   fWeightMatrix0to1[0][5] = 0.903560478621349;
   fWeightMatrix0to1[1][5] = 1.39026572698396;
   fWeightMatrix0to1[2][5] = -1.36645389364439;
   fWeightMatrix0to1[3][5] = 1.77399205969113;
   fWeightMatrix0to1[4][5] = -2.14368887403591;
   fWeightMatrix0to1[5][5] = -2.04533722648467;
   fWeightMatrix0to1[6][5] = -7.37221087511729;
   fWeightMatrix0to1[7][5] = -2.34326184972304;
   fWeightMatrix0to1[8][5] = 0.349942553946249;
   fWeightMatrix0to1[9][5] = -1.44712874214419;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.457887420421731;
   fWeightMatrix1to2[0][1] = 0.505639535189327;
   fWeightMatrix1to2[0][2] = -0.455812079180477;
   fWeightMatrix1to2[0][3] = 0.236897581551876;
   fWeightMatrix1to2[0][4] = 0.910791878049748;
   fWeightMatrix1to2[0][5] = 0.492473932024155;
   fWeightMatrix1to2[0][6] = -0.776874660116326;
   fWeightMatrix1to2[0][7] = -1.38252912878383;
   fWeightMatrix1to2[0][8] = 0.455314899914145;
   fWeightMatrix1to2[0][9] = 0.352290533238802;
   fWeightMatrix1to2[0][10] = -0.310861635475458;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5.52172231674;
   fMax_1[0][0] = 14.1277580261;
   fMin_1[1][0] = 5.52216863632;
   fMax_1[1][0] = 14.3609724045;
   fMin_1[2][0] = 5.52172231674;
   fMax_1[2][0] = 14.3609724045;
   fMin_1[0][1] = -8.89601802826;
   fMax_1[0][1] = 2.99134349823;
   fMin_1[1][1] = -4.52225160599;
   fMax_1[1][1] = 2.99566316605;
   fMin_1[2][1] = -8.89601802826;
   fMax_1[2][1] = 2.99566316605;
   fMin_1[0][2] = -4.45417881012;
   fMax_1[0][2] = 2.30202627182;
   fMin_1[1][2] = -2.44079780579;
   fMax_1[1][2] = 2.29882144928;
   fMin_1[2][2] = -4.45417881012;
   fMax_1[2][2] = 2.30202627182;
   fMin_1[0][3] = 0.119257897139;
   fMax_1[0][3] = 74.6488189697;
   fMin_1[1][3] = 0.0247707404196;
   fMax_1[1][3] = 41.5921821594;
   fMin_1[2][3] = 0.0247707404196;
   fMax_1[2][3] = 74.6488189697;
   fMin_1[0][4] = 1.91479802132;
   fMax_1[0][4] = 6.49894762039;
   fMin_1[1][4] = 2.06325936317;
   fMax_1[1][4] = 8.57907009125;
   fMin_1[2][4] = 1.91479802132;
   fMax_1[2][4] = 8.57907009125;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
