// Class: ReadFisher
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Fisher::Fisher
TMVA Release   : 4.0.7         [262151]
ROOT Release   : 5.27/04       [334596]
Creator        : hluo
Date           : Mon Apr 22 15:03:22 2013
Host           : Linux lxbuild148.cern.ch 2.6.18-164.11.1.el5 #1 SMP Wed Jan 20 12:36:24 CET 2010 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/user/h/hluo/cmtuser/tmva
Training events: 47065
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
Method: "Fisher" [Discrimination method]
# Default:
VerbosityLevel: "Default" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
Log_Bs_fd                     Log_Bs_fd                     Log_Bs_fd                     Log_Bs_fd                                                       'F'    [3.91209959984,15.4932832718]
Log_Bs_ip                     Log_Bs_ip                     Log_Bs_ip                     Log_Bs_ip                                                       'F'    [-13.8155107498,8.27712917328]
Log_ipmin                     Log_ipmin                     Log_ipmin                     Log_ipmin                                                       'F'    [2.77259969711,9.80004501343]
Bs_CHI2                       Bs_CHI2                       Bs_CHI2                       Bs_CHI2                                                         'F'    [0.413907945156,146.147994995]
Log_Bs_evchi2                 Log_Bs_evchi2                 Log_Bs_evchi2                 Log_Bs_evchi2                                                   'F'    [-4.45684528351,2.19719600677]
Log_chi2max                   Log_chi2max                   Log_chi2max                   Log_chi2max                                                     'F'    [-0.54315662384,1.38620865345]
Bspt                          Bspt                          Bspt                          Bspt                                                            'F'    [2.04633593559,11.0426483154]
Meson_pt                      Meson_pt                      Meson_pt                      Meson_pt                                                        'F'    [6.7888007164,9.98982334137]
Meson_ip                      Meson_ip                      Meson_ip                      Meson_ip                                                        'F'    [-6.31357955933,10.68309021]
Log_ptmin                     Log_ptmin                     Log_ptmin                     Log_ptmin                                                       'F'    [5.52178239822,8.89382553101]
eta_angle1                    eta_angle1                    eta_angle1                    eta_angle1                                                      'F'    [1.85206079483,9.68502902985]
phi_ENDVERTEX_CHI2            phi_ENDVERTEX_CHI2            phi_ENDVERTEX_CHI2            phi_ENDVERTEX_CHI2                                              'F'    [1.636056568e-10,8.99912834167]
f0_ENDVERTEX_CHI2             f0_ENDVERTEX_CHI2             f0_ENDVERTEX_CHI2             f0_ENDVERTEX_CHI2                                               'F'    [2.45534759191e-10,8.99219608307]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   Bool_t IsStatusClean() const { return fStatusIsClean; }

 protected:

   Bool_t fStatusIsClean;
};

#endif

class ReadFisher : public IClassifierReader {

 public:

   // constructor
   ReadFisher( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadFisher" ),
        fNvars( 13 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Log_Bs_fd", "Log_Bs_ip", "Log_ipmin", "Bs_CHI2", "Log_Bs_evchi2", "Log_chi2max", "Bspt", "Meson_pt", "Meson_ip", "Log_ptmin", "eta_angle1", "phi_ENDVERTEX_CHI2", "f0_ENDVERTEX_CHI2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 3.91209959983826;
      fVmax[0] = 15.4932832717896;
      fVmin[1] = -13.8155107498169;
      fVmax[1] = 8.27712917327881;
      fVmin[2] = 2.77259969711304;
      fVmax[2] = 9.80004501342773;
      fVmin[3] = 0.413907945156097;
      fVmax[3] = 146.147994995117;
      fVmin[4] = -4.4568452835083;
      fVmax[4] = 2.1971960067749;
      fVmin[5] = -0.543156623840332;
      fVmax[5] = 1.38620865345001;
      fVmin[6] = 2.04633593559265;
      fVmax[6] = 11.0426483154297;
      fVmin[7] = 6.78880071640015;
      fVmax[7] = 9.98982334136963;
      fVmin[8] = -6.31357955932617;
      fVmax[8] = 10.6830902099609;
      fVmin[9] = 5.52178239822388;
      fVmax[9] = 8.89382553100586;
      fVmin[10] = 1.85206079483032;
      fVmax[10] = 9.68502902984619;
      fVmin[11] = 1.63605656799959e-10;
      fVmax[11] = 8.9991283416748;
      fVmin[12] = 2.45534759191202e-10;
      fVmax[12] = 8.99219608306885;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadFisher() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const Bool_t fIsNormalised;
   Bool_t IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   double              fFisher0;
   std::vector<double> fFisherCoefficients;
};

inline void ReadFisher::Initialize() 
{
   fFisher0 = -0.609055177684;
   fFisherCoefficients.push_back( 0.0885964580212 );
   fFisherCoefficients.push_back( -0.1315446392 );
   fFisherCoefficients.push_back( -0.0298882384901 );
   fFisherCoefficients.push_back( -0.00338632669839 );
   fFisherCoefficients.push_back( -0.199274068115 );
   fFisherCoefficients.push_back( -0.568051278747 );
   fFisherCoefficients.push_back( 0.0555057008165 );
   fFisherCoefficients.push_back( -0.0291284111531 );
   fFisherCoefficients.push_back( 0.0909874084713 );
   fFisherCoefficients.push_back( 0.0923690910075 );
   fFisherCoefficients.push_back( -0.116018972936 );
   fFisherCoefficients.push_back( 0.0243944256377 );
   fFisherCoefficients.push_back( 0.00367010543793 );

   // sanity check
   if (fFisherCoefficients.size() != fNvars) {
      std::cout << "Problem in class \"" << fClassName << "\"::Initialize: mismatch in number of input values"
                << fFisherCoefficients.size() << " != " << fNvars << std::endl;
      fStatusIsClean = false;
   }         
}

inline double ReadFisher::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double retval = fFisher0;
   for (size_t ivar = 0; ivar < fNvars; ivar++) {
      retval += fFisherCoefficients[ivar]*inputValues[ivar];
   }

   return retval;
}

// Clean up
inline void ReadFisher::Clear() 
{
   // clear coefficients
   fFisherCoefficients.clear(); 
}
   inline double ReadFisher::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
