// Class: ReadSVM
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : SVM::SVM
TMVA Release   : 4.0.7         [262151]
ROOT Release   : 5.27/04       [334596]
Creator        : hluo
Date           : Mon Apr 22 15:35:58 2013
Host           : Linux lxbuild148.cern.ch 2.6.18-164.11.1.el5 #1 SMP Wed Jan 20 12:36:24 CET 2010 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/user/h/hluo/cmtuser/tmva
Training events: 47065
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
Tol: "1.000000e-03" [Tolerance parameter]
Gamma: "2.500000e-01" [RBF kernel parameter: Gamma]
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
C: "1.000000e+00" [Cost parameter]
MaxIter: "1000" [Maximum number of training loops]
NSubSets: "1" [Number of training subsets]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
Log_Bs_fd                     Log_Bs_fd                     Log_Bs_fd                     Log_Bs_fd                                                       'F'    [3.91209959984,15.4932832718]
Log_Bs_ip                     Log_Bs_ip                     Log_Bs_ip                     Log_Bs_ip                                                       'F'    [-13.8155107498,8.27712917328]
Log_ipmin                     Log_ipmin                     Log_ipmin                     Log_ipmin                                                       'F'    [2.77259969711,9.80004501343]
Bs_CHI2                       Bs_CHI2                       Bs_CHI2                       Bs_CHI2                                                         'F'    [0.413907945156,146.147994995]
Log_Bs_evchi2                 Log_Bs_evchi2                 Log_Bs_evchi2                 Log_Bs_evchi2                                                   'F'    [-4.45684528351,2.19719600677]
Log_chi2max                   Log_chi2max                   Log_chi2max                   Log_chi2max                                                     'F'    [-0.54315662384,1.38620865345]
Bspt                          Bspt                          Bspt                          Bspt                                                            'F'    [2.04633593559,11.0426483154]
Meson_pt                      Meson_pt                      Meson_pt                      Meson_pt                                                        'F'    [6.7888007164,9.98982334137]
Meson_ip                      Meson_ip                      Meson_ip                      Meson_ip                                                        'F'    [-6.31357955933,10.68309021]
Log_ptmin                     Log_ptmin                     Log_ptmin                     Log_ptmin                                                       'F'    [5.52178239822,8.89382553101]
eta_angle1                    eta_angle1                    eta_angle1                    eta_angle1                                                      'F'    [1.85206079483,9.68502902985]
phi_ENDVERTEX_CHI2            phi_ENDVERTEX_CHI2            phi_ENDVERTEX_CHI2            phi_ENDVERTEX_CHI2                                              'F'    [1.636056568e-10,8.99912834167]
f0_ENDVERTEX_CHI2             f0_ENDVERTEX_CHI2             f0_ENDVERTEX_CHI2             f0_ENDVERTEX_CHI2                                               'F'    [2.45534759191e-10,8.99219608307]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   Bool_t IsStatusClean() const { return fStatusIsClean; }

 protected:

   Bool_t fStatusIsClean;
};

#endif

class ReadSVM : public IClassifierReader {

 public:

   // constructor
   ReadSVM( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadSVM" ),
        fNvars( 13 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "Log_Bs_fd", "Log_Bs_ip", "Log_ipmin", "Bs_CHI2", "Log_Bs_evchi2", "Log_chi2max", "Bspt", "Meson_pt", "Meson_ip", "Log_ptmin", "eta_angle1", "phi_ENDVERTEX_CHI2", "f0_ENDVERTEX_CHI2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 0.99999988079071;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadSVM() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][13];
   double fMax_1[3][13];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const Bool_t fIsNormalised;
   Bool_t IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadSVM"
   inline double ReadSVM::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadSVM::InitTransform_1()
{
   fMin_1[0][0] = 4.01541137695;
   fMax_1[0][0] = 13.6988792419;
   fMin_1[1][0] = 3.91209959984;
   fMax_1[1][0] = 15.4932832718;
   fMin_1[2][0] = 3.91209959984;
   fMax_1[2][0] = 15.4932832718;
   fMin_1[0][1] = -10.0326366425;
   fMax_1[0][1] = 3.21743774414;
   fMin_1[1][1] = -13.8155107498;
   fMax_1[1][1] = 8.27712917328;
   fMin_1[2][1] = -13.8155107498;
   fMax_1[2][1] = 8.27712917328;
   fMin_1[0][2] = 2.77262210846;
   fMax_1[0][2] = 9.80004501343;
   fMin_1[1][2] = 2.77259969711;
   fMax_1[1][2] = 9.80004501343;
   fMin_1[2][2] = 2.77259969711;
   fMax_1[2][2] = 9.80004501343;
   fMin_1[0][3] = 0.934173703194;
   fMax_1[0][3] = 119.228057861;
   fMin_1[1][3] = 0.413907945156;
   fMax_1[1][3] = 146.147994995;
   fMin_1[2][3] = 0.413907945156;
   fMax_1[2][3] = 146.147994995;
   fMin_1[0][4] = -4.45684528351;
   fMax_1[0][4] = 2.19674921036;
   fMin_1[1][4] = -4.45684528351;
   fMax_1[1][4] = 2.19719600677;
   fMin_1[2][4] = -4.45684528351;
   fMax_1[2][4] = 2.19719600677;
   fMin_1[0][5] = -0.54315662384;
   fMax_1[0][5] = 1.3860886097;
   fMin_1[1][5] = -0.54315662384;
   fMax_1[1][5] = 1.38620865345;
   fMin_1[2][5] = -0.54315662384;
   fMax_1[2][5] = 1.38620865345;
   fMin_1[0][6] = 2.50355529785;
   fMax_1[0][6] = 11.0426483154;
   fMin_1[1][6] = 2.04633593559;
   fMax_1[1][6] = 11.0426483154;
   fMin_1[2][6] = 2.04633593559;
   fMax_1[2][6] = 11.0426483154;
   fMin_1[0][7] = 6.80229616165;
   fMax_1[0][7] = 9.91624355316;
   fMin_1[1][7] = 6.7888007164;
   fMax_1[1][7] = 9.98982334137;
   fMin_1[2][7] = 6.7888007164;
   fMax_1[2][7] = 9.98982334137;
   fMin_1[0][8] = -0.356258809566;
   fMax_1[0][8] = 10.68309021;
   fMin_1[1][8] = -6.31357955933;
   fMax_1[1][8] = 10.68309021;
   fMin_1[2][8] = -6.31357955933;
   fMax_1[2][8] = 10.68309021;
   fMin_1[0][9] = 5.52181959152;
   fMax_1[0][9] = 8.89382553101;
   fMin_1[1][9] = 5.52178239822;
   fMax_1[1][9] = 8.89382553101;
   fMin_1[2][9] = 5.52178239822;
   fMax_1[2][9] = 8.89382553101;
   fMin_1[0][10] = 1.85206079483;
   fMax_1[0][10] = 9.68502902985;
   fMin_1[1][10] = 1.85206079483;
   fMax_1[1][10] = 9.68502902985;
   fMin_1[2][10] = 1.85206079483;
   fMax_1[2][10] = 9.68502902985;
   fMin_1[0][11] = 1.636056568e-10;
   fMax_1[0][11] = 8.99912834167;
   fMin_1[1][11] = 1.636056568e-10;
   fMax_1[1][11] = 8.99912834167;
   fMin_1[2][11] = 1.636056568e-10;
   fMax_1[2][11] = 8.99912834167;
   fMin_1[0][12] = 2.45534759191e-10;
   fMax_1[0][12] = 8.99139595032;
   fMin_1[1][12] = 2.45534759191e-10;
   fMax_1[1][12] = 8.99219608307;
   fMin_1[2][12] = 2.45534759191e-10;
   fMax_1[2][12] = 8.99219608307;
}

//_______________________________________________________________________
inline void ReadSVM::Transform_1( std::vector<double>& iv, int cls) const
{
if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
   else cls = 2;
}
   for (int ivar=0;ivar<13;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[ivar] = (iv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadSVM::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadSVM::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
